language: go

go:
  - 1.11.x
  - tip

env:
  - GO111MODULE=on

install:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck

script:
  - go test -v -race ./...
  - golint -set_exit_status
  - staticcheck ./...
